project_name: sub2sing-box
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - "386"
    ldflags:
      - -s -w
    no_unique_dist_dir: true
    binary: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
archives:
  - format: binary