when:
  event: tag

steps:
  - name: build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64,linux/arm64,linux/arm/v7
      repo: nite07/sub2sing-box
      auto_tag: true
      username: nite07
      password:
        from_secret: docker_password
