when:
  - event: tag
    ref: refs/tags/v*

steps:
  - name: prepare-tags
    image: bash
    commands:
      - |
        echo "${CI_COMMIT_TAG##v}" > .tags
        if ! echo "${CI_COMMIT_TAG}" | grep -Eq "beta|alpha"; then
          echo "latest" > .tags
        fi
  - name: build
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      repo: nite07/sub2sing-box
      username: nite07
      password:
        from_secret: docker_password
