when:
  - event: tag
    ref: refs/tags/v*

steps:
  - name: build
    image: goreleaser/goreleaser:latest
    commands:
      - goreleaser release --clean --skip publish
      - mkdir release
      - mv dist/*.tar.gz release/
      - mv dist/*.zip release/
  - name: release
    image: woodpeckerci/plugin-gitea-release
    settings:
      files: release/*
      api_key:
        from_secret: forgejo_token
      base-url: https://git.nite07.com
      draft: true
