name: Build and Release(Beta)

on:
  push:
    tags:
      - "v[0-9].[0-9].[0-9]-beta*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5

      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean -f .goreleaser.pre.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
